accounts/urls.py
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from .views import *

app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view()),
    path('logout/', LogoutView.as_view()),
    #path('', include('django.contrib.auth.urls')),
    path('change-password/', auth_views.PasswordChangeView.as_view()),
    path('player_registration/', PlayerRegistrationView.as_view(), name="Player_registraion"),
    path('club_registration/', ClubRegistrationView.as_view(), name="club_registration"),
    path('<int:pk>/', ProfileDetail.as_view(), name='user_profile'),
    path('<int:pk>/update/', ProfileUpdateView.as_view(), name='user_update'),
    # path('tournament/upcoming', UpcomingTournament.as_view(), name='upcoming_tournament')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

billiardmate/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import HomeView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('tournament/',include('tournament.urls')),
    path('', HomeView.as_view(), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tournament/urls.py
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from .views import *

app_name = 'tournament'

urlpatterns = [
    path('<string>/', UpcomingTournament.as_view(), name='upcoming_tournament'),
    # path('ongoing/', UpcomingTournament.as_view(), name='ongoing_tournament')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/player/index.html
{% extends 'layouts/base.html' %}

{% block title %}Home{% endblock %}

{% block body %}
{% if user.is_authenticated %}
	{%if user.is_active %}
        {% if user.is_player %}
        <h1>Name: {{user}}</h1><br>
        {% for player in playerobj %}
            {% if player.profile_pic %}
                <img src="{{player.profile_pic.url}}"/><br>
            {% endif %}
            <h1>Player Id: {{player.pk}}</h1><br>
            {% if player.home_club %}
                <h1>Home Club: {{player.home_club}}</h1><br>
            {% endif %}
        <form method="GET" action="{% url 'tournament:upcoming_tournament' string='404' %}" name="form1">
            <button type="submit" name="tournament" id="new_game" value="new_game" >New Game</button><br><br>
            <button type="submit" name="tournament" value="tournament_history" id="tournament_history">Tournament History</button><br><br>
            <button type="submit" name="tournament" value="upcoming_tournament" id="upcoming_tournament">Upcoming Tournament</button><br><br>
            <button type="submit" name="tournament" id="onging_tournament" value="onging_tournament">Ongoing Tournament</button><br><br>
            <button type="submit" name="tournament" value="edit" onclick="alert('page is under construction')">Edit</button><br><br>
        </form>
        {% endfor %}
        {% else %}
            <h1>You are not  authorized as a player</h1>
        {% endif %}

    {% else %}
    <h1>This Player is not valid</h1>
    {% endif %}
{% endif %}
{% endblock %}
{% block script %}
    <script>
    $(document).ready(function(){
        console.log('ok');

    });
    $("#onging_tournament").click(function () {
        document.form1.action ="{% url 'tournament:upcoming_tournament' string='ongoing_tournament' %}";
        console.log("ok working");
    });
    $("#upcoming_tournament").click(function () {
        document.form1.action ="{% url 'tournament:upcoming_tournament' string='upcoming_tournament' %}";
        console.log("ok working");
    });
    $("#tournament_history").click(function () {
        document.form1.action ="{% url 'tournament:upcoming_tournament' string='tournament_history' %}";
        console.log("ok working");
    });
    $("#new_game").click(function () {
        document.form1.action ="{% url 'tournament:upcoming_tournament' string='new_game' %}";
        console.log("ok working");
    });
  </script>
{% endblock %}

templates/player/newgame.html
{% extends 'layouts/base.html' %}

{% block title %}Home{% endblock %}

{% block body %}
{% if user.is_authenticated %}
	{%if user.is_active %}
        {% for player in playerobj %}

        {% endfor %}
            <p>Date : </p>
            <input type="submit" value="Invite Player" name="inviteformatch">
        {% else %}
            <h1>You are not  authorized as a player</h1>
        {% endif %}

    {% else %}
    <h1>This Player is not valid</h1>

{% endif %}
{% endblock %}

templates/player/player_profile.html
{% extends 'layouts/base.html' %}

{% block title %}Home{% endblock %}

{% block body %}
{% if user.is_authenticated %}
	{%if user.is_active %}
		{%if user.is_club %}
			<h1>You are not allowed here</h1>
		{% elif user.is_a_player == True %}
            <h1>Player Profile:</h1>
            {% for user in userobj %}
                <h3>User Name: {{user.username}}<br></h3>
                <h3>Email: {{user.email}}<br></h3>
                <h3>Phone Number: {{user.phone_number}}<br></h3>
                <h3>Joining Date: {{user.joining_date}}<br></h3>
            {% endfor %}
            {% for player in playerobj %}
                <h3>Date of birth: {{player.date_of_birth}}<br></h3>
                <h3>Nationality: {{player.nationality}}<br></h3>
                <h3>Gender: {{player.gender}}<br></h3>
                <h3>Marital Status: {{player.marital_status}}<br></h3>
                <h3>Home Club: {{player.home_club}}<br></h3>
                <h3>Game Frequency: {{player.gameFrequency}}<br></h3>
                 <img src="/{{player.profile_pic.url}}"/><br>
                <a href="{% url 'accounts:user_update' pk=player.user.pk %}">Edit</a>
            {% endfor %}
        {% elif user.is_admin %}
            <h1>You logged in as admin user</h1>
		{% else %}
			<h1>Login to use the app</h1>
		{% endif %}
	{% else %}
	<h1>You active user</h1>
	{% endif %}

{% else %}
	<h1></h1>
{% endif %}
{% endblock %}

templates/player/player_profile_edit.html
{% extends 'layouts/base.html' %}

{% block title %}Home{% endblock %}

{% block body %}
{% if user.is_authenticated %}
	{%if user.is_active %}
		{%if user.is_club %}
			<h1>You are not allowed here</h1>
		{% elif user.is_a_player == True %}
            <h2>{{c}}</h2>
            <form method="post">
              {% csrf_token %}

                <p>{{form.as_p}}</p>
                <p>{{form2.as_p}}</p>
                <br><br>

              <button type="submit">Save</button>
            </form>

        {% elif user.is_admin %}
            <h1>You logged in as admin user</h1>
		{% else %}
			<h1>Login to use the app</h1>
		{% endif %}
	{% else %}
	<h1>You active user</h1>
	{% endif %}

{% else %}
	<h1></h1>
{% endif %}
{% endblock %}