accounts/urls.py
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from .views import *

app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view()),
    path('logout/', LogoutView.as_view()),
    #path('', include('django.contrib.auth.urls')),
    path('change-password/', auth_views.PasswordChangeView.as_view()),
    path('player_registration/', PlayerRegistrationView.as_view(), name="Player_registraion"),
    path('club_registration/', ClubRegistrationView.as_view(), name="club_registration"),
    path('<int:pk>/', ProfileDetail.as_view(), name='user_profile'),
    path('<int:pk>/update/', ProfileUpdateView.as_view(), name='user_update'),
    # path('tournament/upcoming', UpcomingTournament.as_view(), name='upcoming_tournament')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

billiardmate/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import HomeView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('tournament/',include('tournament.urls')),
    path('', HomeView.as_view(), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layouts/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <title>{% block title %} {% endblock %}</title>

</head>

<body>
    <header>
        {% include 'layouts/navbar.html' %}
    </header>

    <br>


        {% block body %}
            <!-- Html code goes here -->
        {% endblock %}
    <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

    {% block script %}
        <!-- Javscript goes here -->
    {% endblock %}
</body>
</html>

templates/layouts/events.html
{% if messages %}
    <div class="row">
        {% for message in messages %}
            <div class="col-md-12">
                <div class="alert alert-{{ message.tags  }}">{{ message }}</div>
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/layouts/navbar.html
<ul>
    <li><a href="/">Home</a></li>
    {% if user.is_authenticated %}

    {% for u in userobj %}
    {% if u.pk %}
    <li><a href="{% url 'accounts:user_profile' pk=u.pk %}">Profile</a></li>
    {% elif form.pk %}
    <li><a href="{% url 'accounts:user_profile' pk=form.pk %}">Profile</a></li>
    {% endif %}

    {% endfor %}
    <li><a href="#">Settings</a>
        <ul>
            <li><a href="/accounts/change-password/">Change Password</a></li>
        </ul>
    </li>
    <li><a href="/accounts/logout/">Logout</a></li>
    {% else %}
    <li><a href="/accounts/login/">Login</a></li>
    <li><a href="#">Register</a>
        <ul>
            <li><a href="/accounts/player_registration/">Player</a></li>
            <li><a href="/accounts/club_registration/">Club</a></li>
        </ul>
    </li>
    {% endif %}

</ul>